[build-system]
requires = ["flit_core >=3.11,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "tasknotify"
version = "0.1.0"
description = "Headless notify"
authors = [
    {name = "Dylan Maltby"},
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "PyGObject",
    "psutil>=5.3.0",
]

[project.scripts]
tasknotify = "tasknotify:main"

[dependency-groups]
dev = [
    "black",
    "isort",
    "mypy",
    "pygobject-stubs",
    "types-psutil",
]
test = [
    "pytest>=6.2.5",
]

[tool.flit.sdist]
include = [
    "tests/",
]

[tool.isort]
profile = "black"

[tool.mypy]
files = [
    "tasknotify.py",
    "tests/",
]
python_version = "3.10"
strict = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*unix_signal_add_full.*:gi.PyGIDeprecationWarning",
]
